### ISSUE TITLE
Error with auth_middleware and Python 3.6

### ISSUE THREAD

**Issue by morfair** [gnarlychicken/aiohttp_auth#4]
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "lib/python3.6/site-packages/aiohttp/web_protocol.py", line 422, in start
    resp = yield from self._request_handler(request)
  File "lib/python3.6/site-packages/aiohttp/web.py", line 306, in _handle
    resp = yield from handler(request)
  File "lib/python3.6/site-packages/aiohttp_auth/auth/auth.py", line 30, in _middleware_handler
    await policy.process_response(request, response)
  File "lib/python3.6/site-packages/aiohttp_auth/auth/cookie_ticket_auth.py", line 65, in process_response
    if response.started:
AttributeError: 'Response' object has no attribute 'started'

**Comment by salteggs** [comment]
+1 got this when upgrading from aiohttp 1.2.0 to 2.2.3

**Comment by radiophysicist** [comment]
+1

**Comment by radiophysicist** [comment]
Actually the problem seems not to be python 3.6 related.
Responce's '.started' property has been dropped in 
[2.0.0rc1 (2017-03-15)](https://github.com/aio-libs/aiohttp/blob/9cb6f021d271b25a334284f96f899371b56845de/CHANGES.rst#200rc1-2017-03-15)

**Comment by radiophysicist** [comment]
According to [commit](https://github.com/aio-libs/aiohttp/commit/b20a0855c4ea32f4ea23c6a845b081f0e82c987c#diff-7beee55a30afdc8c186a5d9804070391)
['.prepared'](http://aiohttp.readthedocs.io/en/stable/web_reference.html#aiohttp.web.StreamResponse.prepared) should be used instead of '.started'.

**Comment by Killsoft1692** [comment]
+1
i fixed it in my fork:
https://github.com/Killsoft1692/aiohttp_auth
